### ISSUE TITLE
Some feedback from me

### ISSUE THREAD

**Issue by emilyb7** [shiryz/db-morning-challenge#7]
Firstly, really cool. Nice work and I'm very glad you made it about books 💛

Some things we could improve:

1. There are some typos. If you don't mind I'll make a pull request for this ;)

2. Harry Potter was published in 1997. I take this seriously.

3. So far I've only done the warm-up exercise and it was quite hard for a warm-up. I'm not against it being hard, but maybe we can think about giving some more hints?

Going to do the rest in a bit...

But in the meantime, you are better than me at SQL. I'm pretty sure this works as it should, but can you tell me if it's the "right" way?

```SQL
SELECT 
  book_id,
  book_name,
  max_reservation_time,
  library
FROM "public"."books" b1
WHERE max_reservation_time > (
  SELECT
    AVG(max_reservation_time)
  FROM books b2
  WHERE b2.library <= b1.library
  GROUP BY b1.library
);
```

**Comment by shiryz** [comment]
@emilyb7 , 
- feel free to correct any typos :wink: 
- I take Harry Potter seriously as well, we'll need to fact check again (that was google :/)
- It is correct, you don't need the `group by` though, should I add the final result to the readme, and if level  3 is too much , I'll delete it or add that a comment that it's an advanced challenge for those who want to try it at home.

**Comment by emilyb7** [comment]
Oh another thing, I think we should remind them how to set env variables (just to keep things fast). I really had to think about this!

**Comment by emilyb7** [comment]
Just reading the next task. It's probably not that hard, but I've had to read it several times in order to get my head around it. Could we maybe prepare some kind of visualisation of the DB schema? I think that would make it easier to comprehend.

Also, is there a reason why posts have a number as opposed to an ID?

**Comment by emilyb7** [comment]
Oh mostly I was confused because we jumped from books to mentors, and I couldn't see what relation mentors had to books. I guess it's no relation...

**Comment by emilyb7** [comment]
<img width="1181" alt="screen shot 2017-02-20 at 20 31 51" src="https://cloud.githubusercontent.com/assets/17532458/23140827/a9f3eabe-f7ab-11e6-9d4e-25c9b7d7ee5a.png">

haha, look who has the most likes! again, i would very much like to know if my solution is ok 🙂

**Comment by emilyb7** [comment]
level 2 part 2:

```sql
SELECT
  p.num,
  auth.location,
  COUNT(l.*)

FROM posts p
JOIN mentors auth ON auth.name = p.mentor_name
JOIN likes l on l.post_num = p.num
JOIN mentors likers on likers.name = l.mentor_name AND likers.location = auth.location

GROUP BY 
  p.num, 
  auth.location;
```

**Comment by emilyb7** [comment]
OK part 3 done! But it took me ages! And I think my solution is horrible.

Then again, these challenges are really good and I wish we'd had something like this during FAC9!!

```SQL
SELECT 
  location,
  AVG(total_likes)::integer

FROM (
  SELECT
    location,
    COUNT(l.*) "total_likes"

  FROM mentors auth
  JOIN posts p ON p.mentor_name = auth.name
  JOIN likes l ON l.post_num = p.num

  GROUP BY 
    p.num, 
    auth.location
) AS Q1

GROUP BY location;
```

**Comment by shiryz** [comment]
@emilyb7 , sorry for adding these so late :disappointed_relieved: 

- part 3 is horrible, but your solution is perfect, shorter than mine too :smile: 

- part 2.1 can have one less join:
`SELECT COUNT(num), posts.mentor_name FROM posts INNER JOIN likes ON post_num=num GROUP BY posts.mentor_name`

- part 2.2 should look like this:
`SELECT location, post_num FROM mentors INNER JOIN likes ON name=mentor_name`
maybe the wording is over complicating it, do you think I should change it?

**Comment by emilyb7** [comment]
@shiryz oh no, did I completely misunderstand 2.2 or did I just overcomplicate it? I need to practise this stuff...

Anyway, thanks for the feedback, I'm glad it wasn't all wrong 😺
